apiVersion: v1
kind: Secret
metadata:
  name: minio-access-keys
type: Opaque
data:
  S3_ACCESS_KEY: V2RRMGFtcUNrUVlZNlliQlFGNnU=
  S3_SECRET_KEY: dFp0Q1RFM0tQY0VnWmNMWXk2TlhGdFVPVlRZdUdVSUhmWWdkWW5Nbg==