apiVersion: v1
kind: Service
metadata:
  name: assoc-svc
  labels:
    name: assoc-svc
spec:
  type: LoadBalancer
  ports:
    - port: 32000
      targetPort: 8080
      protocol: TCP
  selector:
    name:  association-transaction-node
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: association-transaction-node
spec:
  selector:
    matchLabels:
      name: association-transaction-node
  replicas: 3  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        name: association-transaction-node
    spec:
      containers:
        - name: association-transaction-pod
          image: codeenclave/io.codeenclave.fin.service.transactions:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: task-pv-storage
              mountPath: /tmp/rocksdb-transactions
          env:
            - name: KAFKA_SERVER_URL
              value: "kafka-service.default.svc.cluster.local:9092"
            - name: KAFKA_TRANSACTION_TOPIC
              value: "crux-docs"
            - name: ROCKS_DB_DIRECTORY
              value: "/tmp/rocksdb/"
      volumes:
        - name: task-pv-storage
          hostPath:
            path: /tmp/k8sdata
            type: DirectoryOrCreate
