apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: association-transaction
spec:
  selector:
    matchLabels:
      name: association-transaction-node
  replicas: 1  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        name: association-transaction-node
    spec:
      containers:
        - name: association-transaction-pod
          image: codeenclave/io.codeenclave.fin.service.transactions:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 750m
            requests:
              cpu: 300m
          imagePullPolicy: Always
          volumeMounts:
            - name: task-pv-storage
              mountPath: /tmp/rocksdb
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_SERVER_URL
              value: "my-confluent-cp-kafka.kafka.svc.cluster.local:9092"
            - name: ASSOCIATIONSTORE_KAFKA_DOCUMENTSTORAGE_TOPIC
              value: "association-docs"
            - name: ASSOCIATIONSTORE_KAFKA_DOCMENTTSTORAGE_POLL_DURATION
              value: "1"
            - name: ASSOCIATIONSTORE_KAFKA_TRANSACTIONLOG_TOPIC
              value: "association-tx-log"
            - name: ASSOCIATIONSTORE_KAFKA_TRANSACTIONLOG_POLL_DURATION
              value: "1"
            - name: ASSOCIATIONSTORE_ROCKS_DB_DIRECTORY
              value: "/tmp/rocksdb/$(NODE_NAME)/association"
            - name: TRANSACTIONSTORE_KAFKA_DOCUMENTSTORAGE_TOPIC
              value: "transaction-docs"
            - name: TRANSACTIONSTORE_KAFKA_DOCMENTTSTORAGE_POLL_DURATION
              value: "1"
            - name: TRANSACTIONSTORE_KAFKA_TRANSACTIONLOG_TOPIC
              value: "transaction-tx-log"
            - name: TRANSACTIONSTORE_KAFKA_TRANSACTIONLOG_POLL_DURATION
              value: "1"
            - name: TRANSACTION_ROCKS_DB_DIRECTORY
              value: "/tmp/rocksdb/$(NODE_NAME)/transaction"
            - name: ASSOCIATIONSTORE_S3_SYNC_BUCKET
              value: "associationsync"
            - name: ASSOCIATIONSTORE_S3_SYNC_FREQUENCY
              value: "10"
            - name: TRANSACTIONSTORE_S3_SYNC_BUCKET
              value: "transactionsync"
            - name: TRANSACTIONSTORE_S3_SYNC_FREQUENCY
              value: "10"
            - name: S3_ENDPOINT
              value: "http://minio-1615696290.minio.svc.cluster.local:9000"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-keys
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-keys
                  key: S3_SECRET_KEY

      volumes:
        - name: task-pv-storage
          hostPath:
            path: /tmp/k8sdata
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: assoc-svc
  labels:
    name: assoc-svc
spec:
  type: LoadBalancer
  ports:
    - port: 32000
      targetPort: 8080
      protocol: TCP
  selector:
    name:  association-transaction-node
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: association-transaction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: association-transaction
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
