apiVersion: v1
kind: Service
metadata:
  name: assoc-svc
  labels:
    name: assoc-svc
spec:
  type: LoadBalancer
  ports:
    - port: 32000
      targetPort: 8080
      protocol: TCP
  selector:
    name:  association-transaction-node
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: association-transaction-node
spec:
  selector:
    matchLabels:
      name: association-transaction-node
  replicas: 2  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        name: association-transaction-node
    spec:
      containers:
        - name: association-transaction-pod
          image: codeenclave/io.codeenclave.fin.service.transactions:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: task-pv-storage
              mountPath: /tmp/rocksdb
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_SERVER_URL
              value: "my-confluent-cp-kafka.default.svc.cluster.local:9092"
            - name: ASSOCIATIONSTORE_KAFKA_DOCUMENTSTORAGE_TOPIC
              value: "association-docs"
            - name: ASSOCIATIONSTORE_KAFKA_DOCMENTTSTORAGE_POLL_DURATION
              value: "1"
            - name: ASSOCIATIONSTORE_KAFKA_TRANSACTIONLOG_TOPIC
              value: "association-tx-log"
            - name: ASSOCIATIONSTORE_KAFKA_TRANSACTIONLOG_POLL_DURATION
              value: "1"
            - name: ASSOCIATIONSTORE_ROCKS_DB_DIRECTORY
              value: "/tmp/rocksdb/$(NODE_NAME)/association"
            - name: TRANSACTIONSTORE_KAFKA_DOCUMENTSTORAGE_TOPIC
              value: "transaction-docs"
            - name: TRANSACTIONSTORE_KAFKA_DOCMENTTSTORAGE_POLL_DURATION
              value: "1"
            - name: TRANSACTIONSTORE_KAFKA_TRANSACTIONLOG_TOPIC
              value: "transaction-tx-log"
            - name: TRANSACTIONSTORE_KAFKA_TRANSACTIONLOG_POLL_DURATION
              value: "1"
            - name: TRANSACTION_ROCKS_DB_DIRECTORY
              value: "/tmp/rocksdb/$(NODE_NAME)/transaction"
      volumes:
        - name: task-pv-storage
          hostPath:
            path: /tmp/k8sdata
            type: DirectoryOrCreate
